theme = "blowfish"
baseURL = "https://muriloandrade.dev"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 30
enableEmoji = true

[pagination]
pagerSize = 20
buildDrafts = false
buildFuture = false
enableEmoji = true

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]
