[[main]]
none = "none"

[[main]]
name = "Sobre mim"
pageRef = "about"
identifier = "fQtweViGX3"
weight = 1

[[main]]
name = "Experiências"
pageRef = "experience"
identifier = "7DkDLlhHLx"
weight = 2

[[main]]
name = "Projetos"
pageRef = "projects"
identifier = "A3d7jxTXiH"
weight = 3

[[footer]]
none = "none"
